### ISSUE TITLE
Error importing css from node

### ISSUE THREAD

**Issue by dinoboff** [systemjs/plugin-css#105]
Using jspm 0.17.0-beta-27 and something like that (for running test with mocha):
```
const jspm = require('jspm');
const loader = new jspm.Loader();

loader.import('my-package/some.css!').then(x => console.log(x)).catch(e => console.error(e))
```

I get:

    { (SystemJS) document is not defined
      ReferenceError: document is not defined
          at SystemJSNodeLoader.CSSPluginBase.instantiate (/path/to/jspm_packages/github/systemjs/plugin-css@0.1.27/css-plugin-base.js:60:15)
          at /path/to/jspm_packages/github/systemjs/plugin-css@0.1.27/css.js:121:34
      Error loading /path/to/src/some.css!/path/to/jspm_packages/github/systemjs/plugin-css@0.1.27/css.js
      originalErr:
       ReferenceError: document is not defined
           at SystemJSNodeLoader.CSSPluginBase.instantiate (file:///path/to/jspm_packages/github/systemjs/plugin-css@0.1.27/css-plugin-base.js:60:15)
           at file:///path/to/jspm_packages/github/systemjs/plugin-css@0.1.27/css.js:121:34 }

I would expect the loader to just ignore the import.

**Comment by dinoboff** [comment]
A workaround it to map "css" to plugin-text in the node config (is there better way?).

**Comment by guybedford** [comment]
Yes it would definitely be better to not have this error in Node.

**Comment by guybedford** [comment]
Added in https://github.com/systemjs/plugin-css/commit/8ec7a565dffc2cb0ebd9505d30984800846e24e2.

**Comment by dinoboff** [comment]
Tested with 67d7f0e8 and it's working.

**Comment by guybedford** [comment]
Thanks for the follow-up here.
