### ISSUE TITLE
The `buildCSS` option seems not implemented

### ISSUE THREAD

**Issue by Beldur** [systemjs/plugin-css#107]
Hi,

I tried the `buildCSS` option, without effect.

I searched the [systemjs](https://github.com/systemjs/systemjs), [builder](https://github.com/systemjs/builder) and [plugin-css](https://github.com/systemjs/plugin-css) repositories for any occurrence of `buildCSS` - without result (except the information in the [plugin-css/README.md](https://github.com/systemjs/plugin-css/blob/master/README.md)).

**Comment by mtpc** [comment]
Seconding this.

**Comment by guybedford** [comment]
Thanks, this has been added back in https://github.com/systemjs/plugin-css/commit/b05944ff4b18ac36b4aeedbc0f5c9a1a8a348a72.
