### ISSUE TITLE
Request: return as string option or plugin

### ISSUE THREAD

**Issue by jerryorta-dev** [systemjs/plugin-css#115]
@guybedford 

I forked this plugin and changed it to return an es6 string rather than place a link in the header. This is primarily for Angular 2.0, but others may find it useful. All I really did is combine your plugin-text and left css build stuff.

[See https://github.com/UIUXEngineering/plugin-css-string/blob/master/css.js#L2](https://github.com/UIUXEngineering/plugin-css-string/blob/master/css.js#L2)

Would you consider add this capability to your plugin since this is very close to a duplicate of your work?

I would imagine it would have to be two plugins in one repo.

If this doesn't make sense or is out of scope for this plugin, would you want to own the forked plugin? Again, it's because it's essentially a duplicate of your plugins, and would seem to be a natural fit for maintenance.

If you prefer me to own it, I will just rebase your updates for the build parts when you make them. I can also submit a PR add "css-string" to the jspm registry.

**Comment by guybedford** [comment]
I'm not sure if this work is compatible with the build parts of this project?

If it doesn't need any of the builder code, then it may be more suitable as a separate project I think.

**Comment by jerryorta-dev** [comment]
It's not compatible now that I look at it closer. Thank you @guybedford. I will experiment with the text plugin again as that is supposed to accomplish the same goal. I think something else was an issue with my seed project. If the text plugin still doesn't work, I will make plugin-css-string a seperate project.
