### ISSUE TITLE
Enable safe mode on cssnano by default?

### ISSUE THREAD

**Issue by mayank23** [systemjs/plugin-css#119]
plugin-css 0.1.30 includes cssnano. cssnano will rebase z-index values by default, which broke some of my stuff. Can there be an option to disable or enable safe mode?

z-index rebase optimization: 
http://cssnano.co/optimisations/zindex/

safe mode flag:
http://cssnano.co/options/#optionssafe-bool

Thanks

**Comment by guybedford** [comment]
Safe mode is enabled by default at https://github.com/systemjs/plugin-css/blob/master/css-plugin-base-builder.js#L141 as of version 0.1.32. Ensure you're running this latest version.

**Comment by mayank23** [comment]
Thanks. Missed the update.
