### ISSUE TITLE
Css files bundled as @import

### ISSUE THREAD

**Issue by jperezruiz** [systemjs/plugin-css#126]
I have imports for some css files, when I try to create a bundle, the css of libs are bundled correctly (jquery ui, font-awesome,flexboxgrid) but my css files are bundled with @import
Also, these css files doesn't load properly
![image](https://cloud.githubusercontent.com/assets/11233351/22735762/6beb8772-edfb-11e6-8bf4-f70a0979e7a2.png)
![image](https://cloud.githubusercontent.com/assets/11233351/22735717/3bcdacaa-edfb-11e6-93ec-2c24867d89a4.png)
![image](https://cloud.githubusercontent.com/assets/11233351/22735729/48f44362-edfb-11e6-8fa7-18ce8e91fec0.png)

![image](https://cloud.githubusercontent.com/assets/11233351/22735811/b637a39c-edfb-11e6-812d-47a55a663cd1.png)

I use typescript 2.1.5 with module system, the plugin css  0.1.34 and clean-css.

I tried to put bundleCss:true in config but the same happens. ¿I have to configure something else?

**Comment by sberney** [comment]
The issue with the files not loading correctly is the backslashes in the import statement.

I see that [this commit](https://github.com/systemjs/plugin-css/commit/6cde0648fc234e1a8cac1e0d0733f7c4e0834a95) fixes it, unfortunately that is not included in the tagged release 0.1.32 (the latest).

I have three consecutive import statements, and two of them are resolved to media query imports, and one has its css embedded. The one that is embedded properly was installed using jspm -- it's a package -- `'ladda/dist/ladda-themeless.css'`. The other two are my own css files, `'css/xyz.css'`. I hoped maybe the difference would be the directory name `css`, but renaming it to `dss` did not solve the problem.

For me, this is occurring after an upgrade in jspm, systemjs, and plugin-css. Not sure if media queries were used before, but I don't remember them being there.

**Comment by sberney** [comment]
On further investigation, I've found the last version that worked: 0.1.29. I'm reverting to that for the time being.

**Comment by jperezruiz** [comment]
Thanks for the answer, I installed the version 0.1.29 and works fine.
I'll be waiting for the next update :)

**Comment by t3hmrman** [comment]
For anyone else that might run into this problem --  it seems to happen when you have a bug in your CSS. 

I started running into this, and was seeing a stray `@import` at the top -- the file that was being imported had a CSS bug inside it (a line like `background-color: background-color: #....;` was hanging around).

Instead of reverting versions, binary comment/delete inside the file that's being imported and make sure you don't have a bug in there
