### ISSUE TITLE
Bundling of embedded svg corrupts url references

### ISSUE THREAD

**Issue by kwesterfeld** [systemjs/plugin-css#131]
We are using an inliner to bundle svg into data-uri based css.  When this css is then built using plugin-css, the construct such as this:

   fill="url(#a)"
   clip-path="url(#b)"

are incorrectly modified to something like this:

  fill="url(app/path/a")
  etc.

This is because the url handling in plugin-css is prepending the base url/app path in this case.  Since these url references are referring to the <defs> section of SVG, it would make sense to detect this and avoid making this adjustment.

Pull request on the way to detect url(#, which should be referring to an id vs. absolute path.

**Comment by guybedford** [comment]
Thanks, merged and released in 0.1.34.
