### ISSUE TITLE
"postinstall" script issues

### ISSUE THREAD

**Issue by AlekseyMartynov** [systemjs/plugin-css#133]
In version 0.1.34
https://github.com/systemjs/plugin-css/blob/0.1.34/package.json#L7
installation invokes a nested `npm install` and adds a dependency from GitHub

> ok   Installed postcss-import to github:guybedford/postcss-import@feature/load-source-maps (feature/load-source-maps)

As I understand, plugin users don't need anything from the "build-post-css" directory, and the `postinstall` step is not needed for them, but only complicates package restore procedure.

**Comment by guybedford** [comment]
Thanks for reporting @AlekseyMartynov, this was missed from PR https://github.com/systemjs/plugin-css/pull/124. I've posted a 0.1.35 with the fix.
