### ISSUE TITLE
How can I avoid adding all the CSS Plugin dependencies to my config.js

### ISSUE THREAD

**Issue by carlosagsmendes** [systemjs/plugin-css#16]
I've posted this as a question in StackOverflow so we can start improving Q&A on JSPM: 

http://stackoverflow.com/questions/28889066/how-to-avoid-adding-the-dependencies-to-config-js-when-installing-jspm-plugins

**Comment by guybedford** [comment]
The plan is to introduce configuration builds that can output the bare minimum configuration needs for specific build scenarios. This is being tracked at https://github.com/systemjs/builder/issues/67.
