### ISSUE TITLE
copyAssets option

### ISSUE THREAD

**Issue by guybedford** [systemjs/plugin-css#23]
An option that copies all CSS assets into the build folder and renormalizes them in the bundled stylesheet.

We could also allow customizing the output folder within the build folder (`build/styles`) etc.

**Comment by JordanBelford** [comment]
I would appreciate a solution like this. Currently I have a gulp task to manually copy font-awesome from jspm_packages to my dist directory, so that requests for its assets don't get 404'd.

**Comment by guybedford** [comment]
This cam up again in https://github.com/systemjs/plugin-css/issues/61, but for SFX-only and could be workable.

**Comment by JordanBelford** [comment]
I am using SFX bundle, so #61 sounds like a promising solution.
