### ISSUE TITLE
Reusing substack/insert-css

### ISSUE THREAD

**Issue by geelen** [systemjs/plugin-css#25]
Was getting started on my postcss loader just to get a feel for how to write a loader. Came up with this, which in dev mode seems to work just like `plugin-css`:

```js
import insertCss from 'insert-css'

export var translate = (load) => {
  insertCss(load.source)
  load.source = ''
}
```

The biggest change I can see is that cross-domain CSS can be loaded from a `link[href]` but the default `fetch` var uses XHR which would blow up. Is that a big deal?

Anyway, I wanted to start a thread about whether it'd be worth rewriting `plugin-css` to reuse as much already out there as possible. It was the first thing I read when I tried to understand the plugin system, and it lead me astray a bit. I didn't realise you could write plugins in ES6, for instance.

**Comment by guybedford** [comment]
Originally when I was working on https://github.com/guybedford/require-css/, I used to use a similar injection method but there were issues with this:
* You need to manually renormalize all URLs on injection
* CORS
* CSS doesn't come up nicely in the dev tools

The last two are the main reasons really.

The injection code does still need to be supplemented with old IE support, which is also hiding in https://github.com/guybedford/require-css/blob/master/css.js waiting to be ported.

This plugin hasn't been given as much attention as it needs though, I do realise. Thanks for showing an interest in this stuff!

**Comment by guybedford** [comment]
Scratch everything I just said.... your point on auto-prefixing makes sense now.

How is the debugging experience looking these days with this approach?

**Comment by geelen** [comment]
Well it's pretty slow! This is me using https://github.com/postcss/postcss-nested and https://github.com/postcss/autoprefixer:

![image](https://cloud.githubusercontent.com/assets/23264/6940304/01647018-d8a8-11e4-9d08-dde33dd52007.png)

![image](https://cloud.githubusercontent.com/assets/23264/6940282/dca8e9c0-d8a7-11e4-8e43-c7a1168942d7.png)

That's compiling this much CSS:
```scss
body {
  background: red;

  > h1 {
    color: blue;
  }
}
```

But this is a very naive implementation, but I'm just sort of exploring at the moment. I thought about maybe using https://github.com/medialize/sass.js/ but for my stuff I don't really need all of SASS. Just autoprefixer, really.

I might try using this next: https://raw.githubusercontent.com/ai/autoprefixer-rails/master/vendor/autoprefixer.js. It's a single-file version, I imagine it'll simplify things hugely.

**Comment by geelen** [comment]
Of course, I just realised the plugin can be published after being built
into a single file - there's no need to load up the plugin's dependencies
one by one...

**Comment by geelen** [comment]
Interesting, by using `jspm build --inject` I can take the total number of files loaded from 166 to 13. It takes the performance from this:

![image](https://cloud.githubusercontent.com/assets/23264/6942894/1e173744-d8bd-11e4-9a4d-674e3254f786.png)

to this:

![image](https://cloud.githubusercontent.com/assets/23264/6942897/27ad34f2-d8bd-11e4-8000-d385ddc9a3e5.png)

This is hosted on Surge, not local btw, so you can better see the difference. I didn't realise how pro `--inject` was :)

**Comment by guybedford** [comment]
Yeah that can often be a good dev workflow. Btw you can do `jspm bundle app/**/* - [app/**/*] -i` to automatically everything not in app.

Specifically when I asked about the debugging - the argument before was that we want to be able to see the line numbers in the CSS file for debugging, that's why we tried to stick with `<link>` tags. Do you know if this is working better for `<style>` approaches now? Have the sourceURLs improved enough now to enable this? Would be the make or break for me.

**Comment by geelen** [comment]
Holy what? What kind of wizardry is `jspm bundle app/**/* - [app/**/*] -i`! That's crazy!

As for your other question, I'll keep chipping away at this project today using this workflow, see how it feels.

I did have a related question for you though - if I wanted to publish a `plugin-autoprefixer` module, that was as simple as https://github.com/geelen/slabify/blob/24f0568f07736c4e66f6048b3762f42593637775/src/postcss.js, can I ship it 'pre-bundled'? So that by default, adding the `autoprefixer` plugin only added 1 extra file to your dev workflow, rather than 150+?

I started to understand the bundle format last night, I can't believe how simple it is — just a collection of `System.register` calls. I assumed there'd be all this boilerplate like in a browserify bundle or like in `build-sfx`. So the bundle format is probably sufficient, but I'd need whatever I publish to inject the bundle definitions to the user's project. Something like:

```js
// autoprefixer/index.js
System.config.bundles["autoprefixer"] = { /* same config as using --inject */ }
System.register( ... ) // All the register calls from the current bundle file
```

That make any kind of sense?

**Comment by geelen** [comment]
Yeah ok this isn't ideal: 
![image](https://cloud.githubusercontent.com/assets/23264/6957118/6147748a-d92a-11e4-8a6d-92a483896f14.png)

I'll see if I can figure out a way to use a`<link>` tag instead but still doing all the work in `translate`.

**Comment by geelen** [comment]
Success! By making use of `URL.createObjectURL`, I can do the transformation & inject `<link>` tags. This is what you get:

![image](https://cloud.githubusercontent.com/assets/23264/6957371/9b112dda-d92c-11e4-9702-a8864819c527.png)

Clicking on the top one:

![image](https://cloud.githubusercontent.com/assets/23264/6957377/abd33a6e-d92c-11e4-86e2-353fd132b537.png)

Theoretically we should be able to get source maps working here, right?

**Comment by guybedford** [comment]
Awesome!! I think source maps would definitely work with that via a sourceURL comment using another blog URL or data-URI. This sounds like it might well be a viable dev workflow then.
