### ISSUE TITLE
Support import 'packagename' automatic resolution.

### ISSUE THREAD

**Issue by Zoltu** [systemjs/plugin-css#26]
Note: I am using Aurelia and I am unclear where the line between what Aurelia is doing and what JSPM is doing and what plugin-css is doing, so I apologize if this isn't a plugin-css issue.

In my application root, I can do `jspm install font-awesome`.
In my JavaScript files, I can do `import 'font-awesome@4.3.0/css/font-awesome.css!'`.
Aurelia or JSPM does some magic and when that JavaScript is run the CSS is applied.

I would very much prefer it if I could instead do `import 'font-awesome!css'`, just like I can do with `import 'bootstrap'`.  In the case of bootstrap, I am actually pulling in the bootstrap JavaScript and that JavaScript pulls in the bootstrap css.  However, in both cases JSPM/SystemJS is doing the resolution of `bootstrap` to `jspm_packages/github/twbs/bootstrap@3.3.2.js`.  Unfortunately, the resolution doesn't happen automatically for CSS files so I am forced to put not only the path, but also the version number of the CSS package.

It is the addition of the version number that is the biggest pain point because it means I can't easily update my CSS dependencies via JSPM alone.  I have to also update the version number in every file in my project that uses that CSS file as well.

If this is a matter of the css files not being packaged in a well defined location, at the least it would be nice if the css plugin did a best-guess.  In many cases (e.g., bootstrap, font-awesome), the css file has a name matching the package name and sitting inside of a css folder.  Perhaps it could at least look for any of the following when resolving the dependency:

* `<package-name>.css`
* `<package-name>.min.css`
* `css/<package-name>.css`
* `css/<package-name>.min.css`

I believe this would catch many of the common cases and allow me to create my own CSS npm/github packages in such a way as to allow the plugin to resolve them.

**Comment by guybedford** [comment]
To use the css plugin without needing the full name, you can do `jspm install css`.

For font-awesome we can certainly add an override to set the "main" property to `./css/font-awesome.css!`. This can be done by adding a file `package-overrides/npm/font-awesome@[version].json` looking like:

```json
{
  "main": "./css/font-awesome.css!",
  "jspmNodeConversion": false
}
```

You can test the above by creating that override file locally and installing with `jspm install font-awesome -o override.json` where override.json is the file above.

Let me know if that works out for you.

**Comment by Zoltu** [comment]
Works just like you said with the exception that there can't be a `.` at the start of the main path.
