### ISSUE TITLE
determine css location on serverside

### ISSUE THREAD

**Issue by u9520107** [systemjs/plugin-css#3]
@guybedford 
I got a weird use case:
Suppose I want to use nomarlize.css. I installed it via jspm, imported as a module, so that css plugin loads it up on the client.
I make the web application to be isomorphic, so most of the html content would be rendered on the server for the initial load. The user experience kinda sucks as normalize only kicks in after javascript starts running.
So I thought perhaps we can list normalize.css to the header and have it loaded first... But the versioning is killing me. Plus if this system is used as a framework.. there may be more than normalize.css that should be loaded, right?
Currently I solved the issue by loading system.js in node, then loads the jspm config file so get all the maps. Then I hacked the plugin-css to return the file path of the module when I do import on the server side:
```
System.import('normalize.css/normalize.css!').then(function (filePath) {...});
```
This way I can dynamically list the css files to the html head, without manually book-keeping the versions. 
What do you think of the use case here? Cuz currently it feels so much like a hack that could break someday...

btw, how does System.locate work? I can't seem to find any documentation on it.

**Comment by guybedford** [comment]
@u9520107 this use case is designed for in SystemJS builder - use the trace API at https://github.com/systemjs/builder#example---exclusion to get the full dependency tree, then just pluck out the CSS files, and you have all the info you need to drop the right link tags in the head. For an example app doing this see https://github.com/Bubblyworld/zygo-server/blob/master/lib/render.js#L24.

**Comment by u9520107** [comment]
@guybedford Thanks, this is pretty cool really. But I noticed that the trace contains a lot of data, and the source codes. Even after i trashed the trace object, the builder itself seems to keep a copy of loaded information. The information could be accessed via builder.loader.loads.
For this use it's like unnecessary data to be kept in memory. Is there a way to clean up the loader?
