### ISSUE TITLE
Preprocessor files loader

### ISSUE THREAD

**Issue by XVincentX** [systemjs/plugin-css#32]
Do you think would be worth to transform this from **plugin-css** to **plugin-style**?
It would be great if it could automatically handle most common preprocessor files (styl, sass, less...)

**Comment by guybedford** [comment]
This will only be a simple CSS plugin, potentially with the ability to add some basic transforms like compiling future CSS features for older browsers.

For handling things like SASS and LESS, the goal is to make it straightforward to "extend" this plugin into a plugin with extra transpilation.

In the mean time the best option is to create custom plugins for each one.

**Comment by XVincentX** [comment]
Thank you for the clarification!
