### ISSUE TITLE
Loading external css?

### ISSUE THREAD

**Issue by PeterKnight** [systemjs/plugin-css#33]
I'm new to systemjs. I'm unsure how to load a stylesheet from an external domain? The paths option described at https://github.com/ModuleLoader/es6-module-loader/wiki/Configuring-the-Loader#paths-implementation doesn't seem to work for css. Is there an example anywhere for loading external css?

**Comment by guybedford** [comment]
You should be able to do this via paths configuration:

```javascript
System.paths['css-file'] = 'http://external-site.com/path/to/css/file.css';
System.import('css-file!css');
```

Just let me know if that's not working for you.

**Comment by PeterKnight** [comment]
Ah!! Now I see. That works, superb. I wasn't appending 'css' after the '!'. Thank you very much.
