### ISSUE TITLE
Can't use `css` as folder name.

### ISSUE THREAD

**Issue by chenxsan** [systemjs/plugin-css#34]
After css plugin installed by running `jspm install css`, we will have a new item added in `config.js`:

```
"css": "github:systemjs/plugin-css@0.1.10",
```
According to [SystemJS Map Configuration](https://github.com/systemjs/systemjs/wiki/Map-Configuration), `css` is a module name, `github:systemjs/plugin-css@0.1.10` is a location.

Then here comes the problem, I had a `app.css` file under a folder named `css` beside `index.html`, the tree described as below:

```
+ index.html
+ css
  + app.css
```

In `index.html` file, I would like to import the `app.css` file:

```
System.import('css/app.css!css');
```
Refresh the `index.html` file in web browser, I would get a http request for `http://localhost:3001/jspm_packages/github/systemjs/plugin-css@0.1.10/app.css`. Because SystemJS took the `css` in `import` as the module name we defined in `map` in config.js file.

Now I need workarounds.

1. Rename the `css` folder name to `mycss` or whatever else, just make sure it won't be conflicted with any keys defined in `map`. Now I can `import` the `app.css` file in `index.html`:

    ```
   System.import('mycss/app.css!css');
   ```

    or
    ```
    System.import('./mycss/app.css!css');
   ```
  Right, the relative path works too.

2. Define a new `paths` in `config.js` file.

    ```
    System.paths["mycss/*"] = "css/*.css";
    ```
    Then we can `import` the `app.css` file in `index.html`:

    ```
   System.import('mycss/app!css');
    ```
3. Rename the `css` key to other one in `map`.

    For example:

    ```
   "style": "github:systemjs/plugin-css@0.1.10",
    ```

   Then we can `import` the `app.css` file in `index.html`:
   ```
System.import('css/app.css!style');
   ```

All these workarounds work, but, it's ugly, and it's weird that we can't name a folder as `css`.

**Comment by Zoltu** [comment]
The fundamental problem here is namespace collision.  JSPM packages are competing for the same namespace as the user's folder structure.  As the number of JSPM packages continues to grow, the chance of collision like this will increase.

The naive solution is to not name packages something that a user *may* want to use as a folder name.  Unfortunately, this doesn't scale terribly well.  :(  That being said, until a better solution is found I believe it would be most reasonable (from a user point of view) to change the name of the css plugin to something like css-plugin.  Is the name `css` necessary to make the suffix matching work?

**Comment by guybedford** [comment]
Yes, one needs to protect against these collisions. The plan is to separate this shared namespace in the naming system of SystemJS by deprecating `System.import('app')` to be baseURL-relative, and only allow `System.import('./app')` to be baseURL-relative. Everything else will need to be configured. This is the new resolution algorithm the spec authors are proposing, whereby everything except _plain names_ are treated as URL relative, while the _plain names_ like `jquery` need to be configured explicitly. Closing as this is a large architectural shift that is in progress.

**Comment by glen-84** [comment]
With https://github.com/systemjs/systemjs/issues/287, this issue could also be resolved by renaming the CSS module to plugin-css and then mapping *.css to this new name.
