### ISSUE TITLE
CSS does not refresh

### ISSUE THREAD

**Issue by zeeshanjan82** [systemjs/plugin-css#35]
I am facing an issue when using the systemjs-angularjs-seed project https://github.com/Swimlane/angular-systemjs-seed
The issue which I am facing is when I define 2 seperate .less files on each of my route in ui-router and when I navigate from one route to another , I do not find the page updating the css , for more on this issue please refer :https://github.com/Swimlane/angular-systemjs-seed/issues/34

**Comment by guybedford** [comment]
Yes, CSS does not refresh. Unloading may be provided as a feature in future, but this is not being prioritsed currently.

Rather the way to handle this is to always ensure styles are fully-modular, and scoped to a parent class that is unique and won't conflict.

**Comment by guybedford** [comment]
See also http://npmjs.org/package/jspm-server here.

**Comment by zeeshanjan82** [comment]
Thanks @guybedford I really appreciate your response. I will have an opportunity soon to implement your recommendation and will revert back with my thoughts and findings.

**Comment by zeeshanjan82** [comment]
@guybedford I am not sure how will jspm-server solve my problem. My problem is that when I have say login screen I need to apply different class to the body tag and when I have the dashboard screen I need to apply different class. I am using angularjs application

**Comment by guybedford** [comment]
@zeeshanjan82 right, yes there is currently no unloading mechanism for css. If you write your css to use specificity so that there are no clashes, then that is really the best solution here.
