### ISSUE TITLE
Support builds for non-jspm users

### ISSUE THREAD

**Issue by guybedford** [systemjs/plugin-css#40]
Using `System._nodeRequire('clean-css')` for example as an npm dependency.

Would go with publishing to npm.

**Comment by guybedford** [comment]
Including separateCSS to stub out css requires.

**Comment by dchambers** [comment]
Hi @guybedford, 

I've been [trying to spike](https://github.com/dchambers/systemjs-mocha-spike) testing SystemJS dependent code directly within Node.js using Mocha, and it seemed to be working until I tried to start using the CSS plug-in, where it just seems to evaluate it as JavaScript (I tried the older plug-in syntax too BTW). Is this spike blocked on this issue, or might it be a different issue?

Additionally, is this issue that is causing you to have this disclaimer on the main page?:

> Currently CSS bundling is only supported in jspm, please post an issue if you would like support outside of jspm.

Thanks as always.

**Comment by guybedford** [comment]
Hey @dchambers, this may be a bug - builds should still work with SystemJS outside of jspm, but the result should be that CSS is not built. If there is an actual error please let me know as that should be something we can resolve.

Specifically this issue is tracking full CSS build support though as well.

**Comment by dchambers** [comment]
Hi @guybedford,

I don't think you would classify this as being a _build_. I'm using `System.import()` within Node.js to retrieve some code that includes CSS imports. It worked fine until I tried to introduce CSS, and I knew it was working because I had to start adding `.js` suffixes to my _require-paths_.

When I run `npm install; npm test` from my [spike](https://github.com/dchambers/systemjs-mocha-spike) then I see this error:

```
dominicc@dominicc-laptop:~/git-dev/systemjs-mocha-spike$ npm test

> systemjs-mocha-spike@0.0.0 test /home/dominicc/git-dev/systemjs-mocha-spike
> mocha --compilers js:babel/register test



  stuff
    1) "before each" hook


  0 passing (43ms)
  1 failing

  1) stuff "before each" hook:
     /home/dominicc/git-dev/systemjs-mocha-spike/node_modules/systemjs/dist/system.src.js:1199
        throw addToError(e, 'Evaluating ' + load.address);
              ^
evalmachine.<anonymous>:1
body {
     ^
Unexpected token {
	Evaluating file:///home/dominicc/git-dev/systemjs-mocha-spike/src/style.css
	Evaluating file:///home/dominicc/git-dev/systemjs-mocha-spike/src/stuff.js
	Error loading file:///home/dominicc/git-dev/systemjs-mocha-spike/src/stuff.js
          throw addToError(e, 'Evaluating ' + load.address);
                ^
  evalmachine.<anonymous>:1
  body {
       ^
  SyntaxError: Unexpected token {
      at Object.exports.runInThisContext (vm.js:73:16)
      at Object.<anonymous> (evalmachine.<anonymous>:1:69)
      at evalmachine.<anonymous>:5:4
      at Object.exports.runInThisContext (vm.js:74:17)
```

The problem you are seeing here is that it's trying to evaluate CSS code as JavaScript. The spike is currently using config to handle a `style.css` file, but I also got the same error when I tried to require `style.css!`.

Is this therefore behaviour that is dependent on this issue?

**Comment by guybedford** [comment]
@dchambers thanks yes that is actually an unrelated bug. I've fixed it in https://github.com/systemjs/systemjs/commit/bd5ecf33847a4dfbdb6664b2a067d0782559dd34 and added a workaround in https://github.com/systemjs/plugin-css/commit/32831abfd40bf57ec86e836560ab3c23f073436f. So it should work on SystemJS master or CSS master now.

**Comment by dchambers** [comment]
Damn your quick! I'll test it when I'm back in the office...

**Comment by dchambers** [comment]
@guybedford, I quickly tried applying both of the patches you linked and it didn't seem to help, but I'll try having a more detailed look at this later tonight. Thanks again :+1:

**Comment by guybedford** [comment]
Note you do need to use the `.css!` syntax.

**Comment by dchambers** [comment]
Okay, thanks for the warning. Using that notation hasn't helped me either, but I'll try debugging properly tonight when I can make more time available...

**Comment by guybedford** [comment]
We now support installing and use without css builds for non jspm users.

**Comment by breandr** [comment]
I all of a sudden started receiving `Unexpected token {` on all of my css imports (`import 'jquery-ui/themes/ui-lightness/jquery-ui.css!';`) after running an `npm update`. Any ideas?

**Comment by guybedford** [comment]
@breandr this sounds like it may be a regression in CleanCSS. Did a further update fix it? Otherwise perhaps lock the version of CleanCSS to the last known version that worked for you here.

**Comment by breandr** [comment]
Yes, an update the day after fixed this. Thanks
