### ISSUE TITLE
Duplicate CSS properties get removed erroneously

### ISSUE THREAD

**Issue by MajorBreakfast** [systemjs/plugin-css#41]
I just noticed that when I create a bundle, it automatically minimizes the css. With this as input:

```CSS
display: -webkit-flex;
display: flex;
```

The resulting CSS is just this:

```CSS
display: flex;
```

@guybedford Can you disable advanced stuff (`advanced: false`) of clean-css by default? I'd be nice if it were opt-in. I didn't expect that a `jspm bundle` alters how my CSS works. It should work the same whether I bundle or not. These optimizations are a tricky business.

**Comment by guybedford** [comment]
I've added a `cssOptimize: false` build option to master.

**Comment by guybedford** [comment]
Correction - `cssOptimizations: false`

**Comment by guybedford** [comment]
Actually I do prefer `cssOptimize: false` have changed it to that!

**Comment by MajorBreakfast** [comment]
- I think that most lines aren't needed since `advanced` triggers them all at once https://github.com/systemjs/plugin-css/blob/master/css-builder.js#L46-L50
- I really think that enabling optimization by default is a bad idea. It's not enabled by default for javascript either precisely because it can (and in my case definitely does) cause trouble.

**Comment by guybedford** [comment]
@MajorBreakfast good point - I've adjusted this in https://github.com/systemjs/plugin-css/commit/b66470f066173142f21162452b99785ea5d0f8a1. Will post a release shortly.

**Comment by MajorBreakfast** [comment]
Thx. That should do it.
