### ISSUE TITLE
plugin requires standard node modules

### ISSUE THREAD

**Issue by agrishun** [systemjs/plugin-css#42]
Hi
When I'm trying to build my project with css, I've got this error
Error: Error: ENOENT, open '/Users/username/Documents/dev/module-example/fs.js'
My current versions are

```
"systemjs": "^0.17.1",
"jspm": "^0.16.0-beta",
```
This is strange, because I have all dependencies for this plugin

```
"github:systemjs/plugin-css@0.1.12": {
      "clean-css": "npm:clean-css@3.1.9",
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "path": "github:jspm/nodelibs-path@0.1.0"
},
```

Not sure if i'm doing smth wrong.

**Comment by guybedford** [comment]
Thanks for posting - could you try running the latest beta (0.16.0-beta.2) and let me know if that fixes this?

**Comment by agrishun** [comment]
I've updated now up to 0.16.0-beta.2 but it's still the same. 
Actually, this error disappeared yesterday after some manipulation with npm/jspm

Now I've got this
```
Error loading file:///Users/username/Documents/dev/module-example/clean-css.js from file:///Users/username/Documents/dev/module-example/jspm_packages/github/systemjs/plugin-css@0.1.12/css-builder.js
```
Seems like a general problem with requiring modules

**Comment by guybedford** [comment]
You need to use `jspm install css` to load this library with build support. There will be improved support for non jspm installs of the plugin though in the coming release.
