### ISSUE TITLE
Need option to avoid minification

### ISSUE THREAD

**Issue by abhijeetkpawar** [systemjs/plugin-css#45]
Currently, even if the `minify` flag is false in `jspm.bundleSFX(...)`, the CSS gets minified.
It would be better to have minfication optional or inferred based on bundling options.

**Comment by guybedford** [comment]
Good point - minification should only happen when `opts.minify` is set.

**Comment by guybedford** [comment]
This is not currently possible with cleanCSS, but will be possible in future when the new postCSS version is used.
