### ISSUE TITLE
Missing dependencies

### ISSUE THREAD

**Issue by admwx7** [systemjs/plugin-css#48]
As of 0.1.13 (also on master) the dependencies are missing from package.json, so running jspm install followed by a bundle after doing a clean of my JSPM is giving me a `[Error: Install Clean CSS via `jspm install npm:clean-css` for CSS build support. Set System.buildCSS = false to skip CSS builds.]` error.

**Comment by guybedford** [comment]
Did you run `jspm install npm:clean-css`?

**Comment by admwx7** [comment]
Yes, that's how I got it working, but from 1.1.12 -> 1.1.13 the dependencies block was removed from the package.json file that included clean-css as a dependency.  This doesn't seem correct since the plugin is clearly dependent on clean-css.  If this was intentional, a section should be added to the readme to let new users know that there's additional steps to getting the plugin to work.

**Comment by nicky-lenaers** [comment]
I'm experiencing this issue aswell. Also, ```jspm install npm:clean-css``` gives my a TypeError, so I tried ```jspm install npm:clean-css -f```. Again the plugin is not installed.

**Comment by guybedford** [comment]
Can you share the error you get on `jspm install npm:clean-css`? Also not sure I follow what you mean when you say the plugin is not installed?

**Comment by nicky-lenaers** [comment]
This is what I get (it's the same with ``-f``, but then it seems to install much more or logs more anyway)

![error](https://cloud.githubusercontent.com/assets/2785350/8963914/ec891292-3622-11e5-83c6-4c6a188a55d2.jpg)

**Comment by guybedford** [comment]
@nicky-lenaers which version of jspm are you running here?

**Comment by nicky-lenaers** [comment]
@guybedford My jspm version: 0.15.7

**Comment by guybedford** [comment]
@nicky-lenaers this was a bug in jspm 0.15, try upgrading.
