### ISSUE TITLE
pass options to clean-css

### ISSUE THREAD

**Issue by devmondo** [systemjs/plugin-css#49]
hi, i want just to use the url rewrite of clean-css , and i dont want it to minify the code or do any other optimizations, how can we pass options for that?

thanks in advanced.

**Comment by guybedford** [comment]
Unfortunately I can't see an option for that in CleanCSS so don't think it is possible.

When we can bring in the new loader work moving over to PostCSS I think that will avoid this.

**Comment by devmondo** [comment]
thanks man :)
