### ISSUE TITLE
import css doesn't bundle file in production

### ISSUE THREAD

**Issue by djindjic** [systemjs/plugin-css#5]
I have this line in my code
```js
import './styles/material.css!css'
```
and everything works perfect in develpoment but it doesn't bundled in my production file with this command:
```bash
jspm bundle app/bootstrap www/bundle/bunde.js --inject --minify
```
Not sure is it a bug, but my console shows:
```
Resource interpreted as Stylesheet but transferred with MIME type text/html
```

**Comment by djindjic** [comment]
Same behavior with:
```js
System.import('styles/material.css!');
```
It could be some hosting issue, but I can't be sure. App is hosted at divshot.io

**Comment by guybedford** [comment]
This sounds like an issue with divshot.io not sending stylesheets with the right content-type set. If you go to the stylesheet URL directly in the browser and look at the network tab, you should be able to see the content-type header being used. It is non-critical though, I wouldn't worry too much about it.

**Comment by djindjic** [comment]
Yes, you are right.
Just one info related to this issue. I am pretty sure that systemjs !text plugin bundles text files into bundle.js, could it be possible with css files too?

**Comment by guybedford** [comment]
Yes this is planned at https://github.com/systemjs/builder/issues/12, I'm hoping to get to it next week.

**Comment by gavriguy** [comment]
+1 for bundling css into the bundle or at least a way to concat all the imported css files into one single file

**Comment by guybedford** [comment]
@gavriguy this was added in the latest jspm and the css plugin 0.1.4.

**Comment by gavriguy** [comment]
Thanks @guybedford
