### ISSUE TITLE
bundling css does not respect order

### ISSUE THREAD

**Issue by devmondo** [systemjs/plugin-css#50]
if i have ```app.js``` which includes ```import ',/wap.css!` ``` and ```home.js``` which includes ```import ',/home.css!` ```

the bundled css file puts ```home.css``` content above ```wap.css```

what i did is
```jspm bundle app + main bundle.js --inject```

i thought bundling respect order, this causes styling nightmare, as css rules priority is important

thanks in advanced.

**Comment by wrldtrvllr** [comment]
Hey guys!
Are there any plans to support this? Even though I understand that systemjs cannot guarantee the loading order when css is loaded dynamically, the builder should be able to preserve the order, no? @devmondo is right, it's really not very intuitive as it would be possible to statically analyze this.

Best regards!
