### ISSUE TITLE
SCSS plugin

### ISSUE THREAD

**Issue by robertbaker** [systemjs/plugin-css#54]
I use node-sass. Would like the ability to import scss directly.

Ideally I would like JSPM/SystemJS to handle importing html partials (angular, SCSS, and Typescript) for me. So I wouldn't need an intermediary compilation step.

**Comment by guybedford** [comment]
There's actually an emscripten version of SASS that can be used to create such a plugin - https://github.com/medialize/sass.js/. Are you interested in working on this yourself?

I'm wondering if perhaps we need a generic plugin repo, where users can post issues for plugin projects in general to try and get more community engagement around plugins. I'd have expected more people to be publishing plugins myself, so it may be a community problem that can be tackled.

**Comment by ScreenDriver** [comment]
I am also using SASS for my stylesheets. Unfortunately I am not experienced enough to implement a SystemJS plugin :disappointed:

**Comment by aaronroberson** [comment]
Found this here:

https://github.com/idcware/node-sass-jspm-importer

I haven't tried it out yet and it appears to only be 4 days old. May be worth getting behind and helping with!

**Comment by screendriver** [comment]
I already made a [SASS Plugin](https://github.com/screendriver/plugin-sass) for SystemJS yesterday and a pull request to be listed in the jspm registry https://github.com/jspm/registry/pull/553

So I believe this issue can be closed.

**Comment by guybedford** [comment]
@screendriver thanks so much for working on this, it's looking really great to me. Have posted a couple of issues on the repo there.
