### ISSUE TITLE
Loading order

### ISSUE THREAD

**Issue by richburdon** [systemjs/plugin-css#57]
This might be a more general systemjs feature/question: is it possible to ensure that CSS gets loaded before the main page loads?

I.e., to replace the need for hard coded package links in the header:

    <link rel="stylesheet" href="/res/packages/github/twbs/bootstrap@3.3.5/css/bootstrap.css">

With something like this (which works, but loads asynchronously -- so you see the raw HTML for half a second before the CSS loads):

    <script type="application/javascript">
      System.import('bootstrap/css/bootstrap.css!');
      System.import('app/test/js/bootstrap.js');
    </script>

**Comment by guybedford** [comment]
We don't provide guarantees for CSS loading order, just like modules. Although the next major release will actually provide this feature as load execution order is set to be deterministic in the latest loader specification.

**Comment by dalgard** [comment]
@guybedford: When you say 'major release' – are we talking about 1.0.0 of SystemJS? Do you have any idea when that will be?

I need to be able to depend on load order in order to override UI library features without adding `!important` statements or inefficient ancestor selectors.

**Comment by guybedford** [comment]
@dalgard unfortunately that update won't be anytime soon, as it requires the whatwg loader spec to be stable first.

**Comment by dazinator** [comment]
I am experiencing this problem..

Is there some javascript event / method of being notified once all dependencies have been loaded? Because I was thinking of perhaps hiding the entire page content, and then once all dependencies loaded, unhide the content. Does this sound workable?

**Comment by dazinator** [comment]
Ok - it was as simple as:

```
  System.import("js/site").then(function(m) { $('.body').show(); });

```

**Comment by djflex68** [comment]
Any updates on this ?

**Comment by dazinator** [comment]
@djflex68 - does ` System.import("js/site").then(function(m) { $('.body').show(); }); ` not work for you - in combination with the css loader plugin?

**Comment by djflex68** [comment]
Unfortunately not in my case. I'm trying to load all CSS files of my application using import directive in a single .ts file. Ordering matters because of CSS selectors precedence.
