### ISSUE TITLE
Copy assets for SFX bundles

### ISSUE THREAD

**Issue by guybedford** [systemjs/plugin-css#61]
Copy all used assets into a folder by the same name as the bundle, with the extension removed and prefixed with `_assets`.

**Comment by guybedford** [comment]
Note this would only be for SFX bundles (detected by `opts.sfx`).

**Comment by guybedford** [comment]
This information may not be available in CleanCSS currently - it may make sense to do this as part of moving the internal CSS optimization process to PostCSS (https://github.com/postcss/postcss).

**Comment by JordanBelford** [comment]
Would this then remap the urls in the bundle to the new assets directory? 
For example, in my SFX bundled js file, I currently have code like the following,

src:url(jspm_packages/npm/font-awesome@4.4.0/fonts/fontawesome-webfont.woff2?v=4.4.0)

So I imagine this feature would copy the assets to bundlename_assets and the url in the bundle would become something like

src:url(bundlename_assets/fontawesome-webfont.woff2?v=4.4.0)

I think that would solve my problem nicely. Help me understand if I'm missing something.

**Comment by patrickmichalina** [comment]
Is this an feature being actively developed? When bundling for production my font-awesome resoruces are not copied over (JSPM is so magically I thought it would be!). Investigation landed me here. I'd love to know what the strategies are to fix this. Is it just to make a gulp task to copy over those resources into dist?

I get this (bundled sfx ran locally): `http://localhost:3000/jspm_packages/npm/font-awesome@4.4.0/fonts/fontawesome-webfont.ttf?v=4.4.0`

**Comment by JordanBelford** [comment]
@patrickmichalina 
My workaround is to copy the font-awesome files to dist with a gulp task.
```javascript
gulp.task('copyCssAssetsWorkaround', function() {
   gulp.src(['jspm_packages/**/font-awesome*/**'])
   .pipe(gulp.dest(path.join(paths.dist, 'jspm_packages')));
});
```

**Comment by patrickmichalina** [comment]
Thanks! I ended up with:

```javascript
gulp.task('font-awesome', function(){
	return gulp.src(['jspm_packages/npm/font-awesome@4.4.0/fonts/**.*'], { "base" : "." })
		.pipe(gulp.dest('dist'));
});
```

... But just wanted to see if JSPM was going to support something that bundles the linked resources. Hope so!

**Comment by guybedford** [comment]
This feature is not currently being actively developed (all issues marked contributions welcome are not under development). If anyone is interested in working on it, please do get in touch.

**Comment by patrickmichalina** [comment]
The last bit of my project that needs to move to CDN (change the url) is the copied assets that aren't bundled. But because the CSS is pointing to the files in the local directory (src: url('../fonts/Material-Design-Iconic-Font.woff2?v=2.1.0')..), I am unsure how to change them. I think I will try to just change the url using gulp-replace for now.

**Comment by ArmorDarks** [comment]
I hope to see that feature in future too.

Bundling libs which have `js`, `css` and images seems to be a problem for now... `js` and `css` can be imported without issues, but there is no easy way to bundle required by css images

**Comment by guybedford** [comment]
The way this feature is planned to be supported is via the SystemJS bundler with the following pattern:

```javascript
builder.bundle('app', { inlinePlugins: false }).then(function(output) {
  // output.assetList then contains the list of CSS file paths in the tree, which can be parsed for assets by other tooling
});
```

If anyone builds a SystemJS Builder wrapper project to handle this please do share.

**Comment by amalahussein** [comment]
Not sure if this related, I can open a new issue if it isnt, but when I run jspm build (format amd), I have a css file I'm importing like this: import 'example.css!', and I've added the css loader as well. 

err  Error: CSS Plugin:
Broken @import declaration of "jspm_packages/github/systemjs/plugin-css@0.1.21/main_theme.css"
    at SystemJSNodeLoader.exports.bundle (file:///Users/ahussein/code/test-app/build/jspm_packages/github/systemjs/plugin-css@0.1.21/css-builder.js:76:13)
    at file:///Users/ahussein/code/test-app/build/jspm_packages/github/systemjs/plugin-css@0.1.21/css.js:89:29

**Comment by guybedford** [comment]
@amalahussein this issue is usually due to a folder name `css/style.css` where the `css` is both the plugin and the folder... this is supposed to be supported when using relative syntax (`import './css/style.css'`) but that is pending bug https://github.com/systemjs/systemjs/issues/1230.

**Comment by ArmorDarks** [comment]
Wouldn't it be easier just to base64 encode assets into bundle, as it doing webpack?

**Comment by patrickmichalina** [comment]
Base encoding adds a lot of extra size to files. I don't think that is the way to go. I personally avoid base64 for files the browser references when at all possible.

**Comment by ArmorDarks** [comment]
One way or another, user have to download those files, and base64 encoded file size isn't that bigger. Though, I can't deny that such approach has caching issues.

Anyway, if it would be easier to implement base64 encoding, it would be much better to have at least it at start than complete absence of bundled assets. Especially considering that in most cases devs will bundle 3rd party libs, which usually have very small assets, and base64 encoding won't hurt them much.

**Comment by ArmorDarks** [comment]
Just wonder, is there any chances to see that feature in any form soon, or it delayed until better times?

**Comment by guybedford** [comment]
This can be done with a file plugin approach like webpack quite easily. But we don't have any plugins that do this. This plugin itself is just a core style loader though, so doesn't fall under this category. Contributions for loaders that offer something similar to the webpack css loading are welcome.

**Comment by ArmorDarks** [comment]
This is very unfortunate, because there are very few developers around capable to write SystemJS plugins, but understandable.

**Comment by guybedford** [comment]
@ArmorDarks for an example of an asset plugin like the Webpack file loader approach see https://github.com/guybedford/asset-plugin-experiment. A CSS plugin could be created that runs resolution through the asset plugin just like webpack. Contributions welcome as I say.

**Comment by guybedford** [comment]
(and CSS plugins can be created easily following the extension mechanism here and example LESS plugin linked from this repo)

**Comment by patrickmichalina** [comment]
@guybedford thanks for sharing :)

**Comment by ArmorDarks** [comment]
@guybedford Thanks, we'll look into it :) You're doing great work with SystemJS and JSPM. I only could wish more people to be able appreciate their benefits.
