### ISSUE TITLE
Using plugin-css with systemjs-csp

### ISSUE THREAD

**Issue by capricube** [systemjs/plugin-css#62]
Hi, 

we are in the process of activating CSP for our application but we are struggling with plugin-css as it is only a CJS module and does not work with systemjs-csp.

What would be the correct way to handle this problem? Should we convert the plugin to a UMD module?

cheers,
Kris

**Comment by guybedford** [comment]
It is possible to convert any file into `System.registerDynamic` by running it through SystemJS builder. This is the `builder.compile` method in https://github.com/systemjs/builder/blob/master/lib/builder.js#L171.

It is currently undocumented as it is still somewhat experimental, but it is well-suited to a gulp task that runs through the files in the app, converting them for CSP support, just like a bundle step but as separate files.

**Comment by capricube** [comment]
thank you very much works as expected. Just in case someone else has the same problem here are the steps i did:

1) compile plugin-css with a simple program using Systemjs.Builder.compile()
```
const path = require('path');
const fs = require('fs-extra');
const jspm = require('jspm');

const builder = new jspm.Builder();

const pluginCssPath = path.join(process.cwd(), "jspm_packages/github/systemjs/plugin-css@0.1.16/css.js");

builder.compile(pluginCssPath).then(function(output) {
	fs.outputFileSync(path.join(process.cwd(), "css-compiled.js"), output.source);
});
```
2) add the module id to the registerDynamic call of the compiled file
instead of
```
System.registerDynamic([], true, function(require, exports, module) {;
```
you get
```
System.registerDynamic('css',[], true, function(require, exports, module) {;
    var global = this,
        __define = global.define;
    global.define = undefined;
```
3) concatenate/copy content of compiled with/into config.js
4) remove `css` plugin from `map`declaration
5) use system-csp-production,js instead of system.js

**Comment by PhilippMi** [comment]
I created a little gulp snippet which handles the first 2 steps:
```javascript
const jspm = require('jspm');
const through2 = require('through2');
const File = require('vinyl');

function precompileCssPlugin() {
    const stream = through2.obj();

    const builder = new jspm.Builder();
    builder.compile("css/css").then(function(output) {

        const file = new File({
            path: "tmp"
        });
        const compiledSource = fixRegistration(output.source);
        const buffer = new Buffer(compiledSource);
        file.contents = buffer;

        stream.push(file);
        stream.push(null);
    });
    return stream;
}

function fixRegistration(source) {
    return source.replace("System.registerDynamic([]",
        "System.registerDynamic('css',[]");
}
```

it can then be used like this:
```javascript
streamqueue.obj(
        gulp.src(['./jspm_packages/system-csp-production.js', './config.js']),
        precompileCssPlugin()
    )
    .pipe(concat('index.js'))
    .pipe(uglify())
    .pipe(gulp.dest('./target/'));
```

**Comment by PhilippMi** [comment]
However, the whole thing does not work with bundling. When I bundle my application using `jspm bundle`, the CSS dependencies are already normalized to `path/to/my.css!github:systemjs/plugin-css@0.1.15`. Hence, the dynamically registered and compiled module is not used anymore.

Do you have any suggestions on how to resolve this issue?

**Comment by capricube** [comment]
i did not test a bundled version of my app. How should we then deal with plugin-css when used in a bundle?

**Comment by guybedford** [comment]
You probably want to use the separateCSS output option for CSP bundling, the CSS can then be included separately with a `<link>` tag alongside the bundle.
