### ISSUE TITLE
Promise never rejected on missing files

### ISSUE THREAD

**Issue by andreas-wagner** [systemjs/plugin-css#63]
The following call to load a file that does not exist always results in the System.import Promise to be fulfilled. But since something bad happened it should be **rejected**!
```javascript
System.import('./styles/does-not-exist.css!').then(
  function(){console.log('ok');},    // onFulfilled
  function(){console.log('oh no');}  // onRejected
);
// => 'ok'
```
If the promise would be rejected, I could try something else or notify the user or whatever. But as it is now I do not even know that it failed at all.

**Comment by guybedford** [comment]
Thanks, I've fixed this in 0.1.18.
