### ISSUE TITLE
Need NPM module for plugin-css

### ISSUE THREAD

**Issue by abhijeetkpawar** [systemjs/plugin-css#66]
Corresponding NPM module will help to organize dependencies appropriately. 
There is one available already (https://www.npmjs.com/package/system-css), but it doesn't seem to be well maintained.

**Comment by geekflyer** [comment]
:+1:

**Comment by pe8ter** [comment]
This would be great.

**Comment by bpostlethwaite** [comment]
This is a fairly trivial fix to get out a basic npm install. Just adding a `name` and `version` field to the package.json will allow installs like
```
npm install plugin-css@git://github.com/systemjs/plugin-css.git#0.1.20
```

While not ideal it'll work.

**Comment by guybedford** [comment]
Thanks @bpostlethwaite. I've published to `systemjs-plugin-css` on npm.

**Comment by bpostlethwaite** [comment]
great thanks!
