### ISSUE TITLE
Invalid regular expression: missing / 

### ISSUE THREAD

**Issue by HansHammel** [systemjs/plugin-css#75]
C:\project>jspm bundle "js/index.js"

leads to "Invalid regular expression: missing / " !?

	C:\project\node_modules\systemjs\dist\system.src.js:1452
	        throw addToError(e.toString(), 'Evaluating ' + load.address);
	        ^
	
	err  SyntaxError: Invalid regular expression: missing /
	        Evaluating file:///C:/project/client/jspm_packages/github/jspm/nodelibs-fs@0.1.2.js
	        Evaluating file:///C:/project/client/jspm_packages/npm/clean-css@3.4.9/lib/imports/inliner.js
	        Evaluating file:///C:/project/client/jspm_packages/npm/clean-css@3.4.9/lib/clean.js
	        Evaluating file:///C:/project/client/jspm_packages/npm/clean-css@3.4.9/index.js
	        Evaluating file:///C:/project/client/jspm_packages/npm/clean-css@3.4.9.js
	        Error loading file:///C:/project/client/jspm_packages/npm/clean-css@3.4.9.js

index.js Content:

	import '../less/styles.css!'; // compiled css

**Comment by guybedford** [comment]
What are the contents of the file at `file:///C:/project/client/jspm_packages/github/jspm/nodelibs-fs@0.1.2.js`?

**Comment by guybedford** [comment]
(that's the file whose execution started the error)

**Comment by HansHammel** [comment]
/* */ 
if (System._nodeRequire) {
  module.exports = System._nodeRequire('fs');
}
else {

  exports.readFileSync = function(address) {
    var output;
    var xhr = new XMLHttpRequest();
    xhr.open('GET', address, false);
    xhr.onreadystatechange = function(e) {
      if (xhr.readyState == 4) {
        var status = xhr.status;
        if ((status > 399 && status < 600) || status == 400) {
          throw 'File read error on ' + address;
        }
        else
          output = xhr.responseText;
      }
    }
    xhr.send(null);
    return output;
  };

}

**Comment by guybedford** [comment]
That looks like the file at `file:///C:/project/client/jspm_packages/github/jspm/nodelibs-fs@0.1.2/fs.js` which I don't think was even loaded here? The specific file in the error message was `file:///C:/project/client/jspm_packages/github/jspm/nodelibs-fs@0.1.2.js`, so I was wondering if that file had somehow got corrupted, say due to running parallel jspm installs.
