### ISSUE TITLE
directory name conflict

### ISSUE THREAD

**Issue by arisAlexis** [systemjs/plugin-css#76]
this:  
import bootstrapCss from 'css/paper-bootstrap.css!';

results in:  
Broken @import declaration of "jspm_packages/github/systemjs/plugin-css@0.1.18/paper-bootstrap.css"

solution: **rename directory to styles**. apparently there is some string splitting or something and confuses it into searching into home dir of plugin-css.

I am using version 1.1.18 maybe it has been fixed in latest versions.

**Comment by guybedford** [comment]
This isn't a bug, it's rather just a common pitfall of the namespacing approach. The atlernative here is to use `import bootstrapCss from './css/paper-boostrap.css!'`. `css/x` will refer to the module `x` within the CSS plugin due to the configuration.

**Comment by arisAlexis** [comment]
ok thanks for the quick reply.
