### ISSUE TITLE
Improve workflow by supporting wildcards in css inclusion

### ISSUE THREAD

**Issue by kwesterfeld** [systemjs/plugin-css#77]
Getting this *up front*: this is not another "load css order" request/issue.   Ordering is not important in my app.

Enhancement request: I would like to support one of the two following syntaxes, to allow breaking css into many disjoint files, but not maintaining a "registry" inclusion in ES6:
```
import 'app/css/*.css!';
```
or 
```
import * from 'app/css/*.css!';
```

The former makes its way through the jspm build process and lands with an error that looks like:
```
>> err  Error: CSS Plugin:
>>      Broken @import declaration of "app/css/*.css"
>>          at file:///Users/...(ommitted).../app/jspm_packages/github/systemjs/plugin-css@0.1.20/css-builder.js:76:13
>> Exited with code: 1.
```

The idea here is that by specifying a wildcard/glob, one can simply drop css into a directory and not wire it up.  Currently, I have 20 or so css fragments that get loaded with imports in a registry.js, which I include with:

 ```
import 'app/css/registry';
```

Near the main entrypoint of my app.

I think this is "fair game" playing outside the ES6 module spec since the css construct with !css is in play here.

**Comment by guybedford** [comment]
Sure, thanks for explaining so clearly - yes I understand the intention here. Wildcard expressions are supported for builds - eg `jspm build app/css/*.css!`, but having the syntax in the import statement itself would not be possible as the loader in the browser doesn't have the ability to request directory listings.

**Comment by kwesterfeld** [comment]
I guess you are saying that because there is (1) development and (2) http/2 unbundled mode in play, making this work for bundled/sfx would perhaps be too special-case?  I see that, disappointed to see it, but I see it.

**Comment by guybedford** [comment]
Yes exactly. But note that SFX case can be handled at build time via `jspm bundle-sfx app/**/*.css! + app/main.js`.

**Comment by kwesterfeld** [comment]
I am definitely bundling the css--super awesome.   I'm inlining gifs and svg, spriting and inlining images,  etc.  The whole app is one download until http/2 is ready for splitting it back apart.   

I was just looking at easing the maintenance of include statements.
