### ISSUE TITLE
The css file always load from cache even I refresh the browser.

### ISSUE THREAD

**Issue by tongjieme** [systemjs/plugin-css#82]
Screen shot of Chrome's network tab:
<img width="568" alt="screen shot 2016-03-30 at 11 40 08 am" src="https://cloud.githubusercontent.com/assets/1511418/14131265/364aa242-f66c-11e5-85ee-e53f9813cdf8.png">

Configuration:
```javascript
System.config({
    map: {
        jquery: 'bower_components/jquery/dist/jquery.js',
        css: 'bower_components/plugin-css/css.js',
        slick: 'bower_components/slick-carousel/slick/slick.js',
        slickCss: 'bower_components/slick-carousel/slick/slick.css'
    },
    meta: {
        '*.css': {
            loader: 'css'
        },
        slick: {
            deps: ['jquery', 'slickCss']
        }
    },
    buildCSS: false
});
```

Demo:
http://116.251.216.179/SystemJS/

**Comment by guybedford** [comment]
Remove your `cache-control` header on the server. Caching is a server-controlled process.

**Comment by tongjieme** [comment]
But doesn't it makes more sense to make a new request to the server when refreshing the browser even there is `cache-control` header on the server? Just like the `<link />` element behavior.
