### ISSUE TITLE
Bundle css imported using System.import()

### ISSUE THREAD

**Issue by zoff** [systemjs/plugin-css#83]
Currently CSS bundling only supports:
`import "./path/file.css!"`

How to bundle css imported with the following?
`System.import("./path/file.css!")`

**Comment by guybedford** [comment]
This would be deferred import tracing, which is being tracked at https://github.com/systemjs/builder/issues/452.

Until then, using addition in the bundle arithmetic is the way to do this - `bundle('main.js + full/path/file.css!')`.
