### ISSUE TITLE
Broken @import declaration of "jspm_packages\github\twbs\bootstrap@3.3.6\css\bootstrap.css"

### ISSUE THREAD

**Issue by born2net** [systemjs/plugin-css#84]
upd from 0.16 to 0.17 and not getting the following error:

![err](https://cloud.githubusercontent.com/assets/5090936/15080451/0f43074c-1373-11e6-816c-05757e885eb7.PNG)

using
"clean-css": "npm:clean-css@3.4.12",

and

```
"src": {
      "main": "App",
      "defaultExtension": "ts",
      "meta": {
        "*.js": {
          "loader": "ts"
        },
        "*.ts": {
          "loader": "ts"
        },
        "*.css": {
          "loader": "css"
        }
      }
```

and my imports are:

```
import 'twbs/bootstrap/dist/css/bootstrap.css';
or
import 'twbs/bootstrap/dist/css/bootstrap.css!';
```

any help is appreciated

regards

Sean

**Comment by guybedford** [comment]
Did you say you had fixed this?

**Comment by born2net** [comment]
sorry it was a config issue on my part so closing.

 Now on a completely different topic do you know of any examples of hot reload with typescript using ng2,  as I could not get that working... tx Guy.
