### ISSUE TITLE
set separateCSS=true, the generated  css file not auto loaded when executing?

### ISSUE THREAD

**Issue by XuJinNet** [systemjs/plugin-css#85]
Hellow, i use SystemJS Build, when set separateCSS=true, the generated css file (bundle.css) not auto loaded when executing, how to resolve this problem?

**Comment by guybedford** [comment]
If the bundle is loaded with the initial page load, then use a link tag. If you are loading this bundle dynamically after the page load, it may be possible to use the `bundles` configuration to do a separate css injection here.
