### ISSUE TITLE
How to resolve path relative to root?

### ISSUE THREAD

**Issue by dougludlow** [systemjs/plugin-css#88]
I'm importing fontawesome and bundling it all up, that's all working fine. The problem I'm running into is that the `.woff` files are being included with the relative url:

```
jspm_packages/npm/font-awesome@4.6.1/fonts/fontawesome-webfont.woff?v=4.6.1
```

When I make a request to `/client/index.html`, requests are made to:

```
/client/jspm_packages/npm/font-awesome@4.6.1/fonts/fontawesome-webfont.woff?v=4.6.1
```

Which results in a 404, as the `jspm_packages` folder is located at the site root.

How do I tell the systemjs-builder/plugin-css to use a path relative to root? Something like this:

```
/jspm_packages/npm/font-awesome@4.6.1/fonts/fontawesome-webfont.woff?v=4.6.1
```

**Comment by guybedford** [comment]
Try setting the `rootURL` configuration option here - https://github.com/systemjs/plugin-css#builder-support. Let me know if that works ok.

**Comment by dougludlow** [comment]
@guybedford it does indeed work now. Curiously, the url now looks like this:
```
../../../../../../jspm_packages/npm/font-awesome@4.6.1/fonts/fontawesome-webfont.eot?v=4.6.1
```
Not exactly sure how it's working. Guess it's just `../`ing so far back it just hits the root and stays there.

**Comment by dougludlow** [comment]
Here's how I'm bundling:

```js
gulp.task('jspm:debug', function(done) {
    var builder = new Builder(),
        options = {
            minify: false,
            sourceMaps: true
        };

    builder.config({
       rootURL: 'file:' + process.cwd()
    });

    builder
        .bundle('client/app/**/* - [client/app/**/*] - [client/app/**/*.tag!]', config.build, options)
        .then(function() {
            browserSync.reload();
            done();
        });
});
```

**Comment by guybedford** [comment]
That seems right I guess. If you hit further relative pathing issues do let me know.
