### ISSUE TITLE
Potentially unhandled rejection in Internet Explorer 10 (ie10)

### ISSUE THREAD

**Issue by siulung4073** [systemjs/plugin-css#89]
Hi there, I'm trying to load a css file from a js file like this: 

`require('./styles/main.css!');`

It works fine everywhere, except on IE10, it throws this error and I cant figure out why:

```
Potentially unhandled rejection [7] Error: Invalid argument.
	   at Anonymous function (eval code:69:7)
	   at init (http://192.168.1.66:3000/jspm_packages/system-polyfills.src.js:382:5)
	   at Promise (http://192.168.1.66:3000/jspm_packages/system-polyfills.src.js:370:4)
	   at loadCSS (eval code:40:5)
	   at fetch (eval code:86:5)
	   at tryCatchReject (http://192.168.1.66:3000/jspm_packages/system-polyfills.src.js:1188:5)
	   at runContinuation1 (http://192.168.1.66:3000/jspm_packages/system-polyfills.src.js:1147:4)
	Error loading http://192.168.1.66:3000/styles/main.css!http://192.168.1.66:3000/jspm_packages/github/systemjs/plugin-css@0.1.22.js 
```

I imported the polyfills for Promise and URL.

If you could point me on the right direction, thanks!

**Comment by guybedford** [comment]
The error above is throwing on this line - https://github.com/systemjs/plugin-css/blob/master/css.js#L69.

I guess you could add a console.log there to see if `console.log(head)`, `console.log(link)` and `console.log(existingLinks[0])` are all properly defined.

Perhaps the `existingLinks[0]` being undefined is the issue, and we need to branch into an appendChild there, I'm not sure though without further testing.

**Comment by siulung4073** [comment]
Hi guy, thanks for the help. I understand this is not a priority whatsoever. 

I added that and this is what is printing:

```
 head: [object HTMLHeadElement] 
 link: [object HTMLLinkElement] 
 existingLinks[0]: undefined 
```

I was able to debug it a bit more, and it seems that when there is no other links added, `existingLinks `is empty, so when it tries to get the first one ` existingLinks[0]` explotes.

I seems that the solution would be to decide where to insert this new link, since there is no existing ones. 

Maybe this part  `head.insertBefore(link, existingLinks[0]);` should change. Or maybe the part where you search for the existing links `function findExistingCSS(url)` , so if its empty you could search for any other link, just to insert it after the last one, or maybe just at the end. I dont know which would be better.

Let me know what you think and maybe I can try to contribute on this one.

thanks!

**Comment by guybedford** [comment]
I'd be happy to update to the following if it works for you:

```javascript
if (existingLinks.length)
  head.insertBefore(link, existingLinks[0]);
else
  head.appendChild(link);
```

**Comment by siulung4073** [comment]
yeah great. If you want I can do it too. Let me know
thanks

**Comment by guybedford** [comment]
Sure, added in https://github.com/systemjs/plugin-css/commit/be718d9726c621b88c5619063adc0d36294947fe.

**Comment by rollermonkey** [comment]
How soon will this be released, I need this fix in the next few days and it would be nice to just pull in the latest official version. Thanks for the work!

**Comment by guybedford** [comment]
I've posted out a release.
