### ISSUE TITLE
Minimal example

### ISSUE THREAD

**Issue by georgewfraser** [systemjs/plugin-css#90]
Please post a minimal example of using jspm with CSS. Despite following the instructions, all I get is "/css not found".

**Comment by JonasGao** [comment]
Very agree, I don't know what to do with it.

**Comment by janblok** [comment]
In the html you need todo something like this:
    <script>
      System.import('main.js').catch(function(err){ console.error(err); });
      System.import('node_modules/bootstrap/dist/css/bootstrap.min.css');
      System.import('node_modules/ngx-bootstrap/datepicker/bs-datepicker.css');
    </script>

this part is missing in the readme
