### ISSUE TITLE
the doc useless!

### ISSUE THREAD

**Issue by JonasGao** [systemjs/plugin-css#91]
when i use "jspm i css", yse, it give me a config.js.

but! where tell me, build.js need load this config.js!

yes! the doc example has "builder.loadConfig('cfg.js')".

but! who know cfg.js is config.js.............

---

This document for people who are new to SystemJS , FRAUGHT!

---

PS: translate by google

**Comment by guybedford** [comment]
Try webpack.

**Comment by JonasGao** [comment]
😂   Yes, Im trying webpack.
