### ISSUE TITLE
Broken @import errors

### ISSUE THREAD

**Issue by mrcasado** [systemjs/plugin-css#96]
Since upgrading from 0.1.23 to 0.1.25  'Broken @import declaration of" when bundling.
I had to go back to 0.1.23.

**Comment by guybedford** [comment]
Can you share a test case? Are you setting the rootURL?

**Comment by mrcasado** [comment]
Sure. 

This is how the bundle task looks:
`   gulp.task('bundle', ['ensure-bundle'], function (cb) {

         var builder = new Builder();
         builder.loadConfig(options.config)
            .then(function() {
               builder.config({
                  buildCSS: true,
                  separateCSS: true
               });
               return builder.buildStatic(options.entryJs, options.outputJs);
            })
            .then(function() {
               gutil.log("Output " + options.outputJs + ", " + options.outputCss);
               cb();
            })
            .catch(function(err) {
               gutil.log('Build error:');
               gutil.log(err);
               cb(err);
            });
      });`

I'm not setting rootURL.

Then I got  in every module(folder) of the project an index.css file with all the css imports like for example ui/controls/src/styles/index.css or ui/crm/src/styles/index.css :
@import "styles/component/event-description.css";
@import "styles/module/recent-events-widget.css";

When bundling using version 0.1.25 I get the following errors:  'Broken @import declaration of "crm/src/styles/component/event-description.css"',
 'Broken @import declaration of "crm/src/styles/module/recent-events-widget.css"',

Do I need to set the rootURL at all?

Thanks
Alex

**Comment by guybedford** [comment]
Thanks, sure I'll test this out as soon as I can.

So it sounds like it is normalizing to `crm/src/styles/module/recent-events-widget.css` which for some reason is invalid? What do you think the correct resolved path should be?

**Comment by guybedford** [comment]
I've just posted out an update in 0.1.26, including some normalization adjustments. If that doesn't fix it for you please let me know, and I'll have another look at this.
