### ISSUE TITLE
Offer UMD build in npm package

### ISSUE THREAD

**Issue by firstdoit** [systemjs/plugin-css#97]
I wonder if you'd consider adding a simple `prepublish` script with something along the lines of: 

`umd css css.js dist/css.umd.js -c`

This would allow people to use it in the browser directly, specially from sources like `npmcdn.com`.

I'm more than happy to submit a PR if this solution is OK. 🙂

**Comment by guybedford** [comment]
This project does load in the browser through SystemJS.. are you saying you'd want the script tag loading support for CSP style loading support?

**Comment by firstdoit** [comment]
@guybedford strange, I must have misconfigured something, then, because I was getting a `exports is undefined` type of error. Let me check again and I'll come right back. 
PS: It would also be good to have a minified version on npm, in any case :)

**Comment by firstdoit** [comment]
Ah, you are correct! It was misconfigured. :)

What about the minified version? That would be useful personally, but I understand if it's not a priority for the project.

**Comment by firstdoit** [comment]
Never mind, we can always come back to this discussion later if you want! :D
