### ISSUE TITLE
HTTP 404 in bundled version for fonts after updating from 0.1.23 to 0.1.25

### ISSUE THREAD

**Issue by Leonidnei** [systemjs/plugin-css#98]
I tried to update to 0.1.25 but got several 404 errors for font-awesome files after bundling the code (we use aurelia).

The failed URLs were one level upper than they should be (e.g. http://localhost/jspm_packages/npm/font-awesome@4.6.3/fonts/fontawesome-webfont.ttf instead of http://localhost/wpl/jspm_packages/npm/font-awesome@4.6.3/fonts/fontawesome-webfont.ttf)

**Comment by guybedford** [comment]
I've posted out a fix in 0.1.26. Please try this out if you can and let me know if you're still getting any issues at all here.

**Comment by Leonidnei** [comment]
Yes, 0.1.26 works fine for us. 
Thanks for quick fix.

**Comment by guybedford** [comment]
Excellent, thanks for the follow-up.
